let mock = [{
    id: 1,
    anime: 'Yahari Ore No Seishun Love Come Wa Machigatteiru',
    character: 'Hachiman Hikigaya',
    quote: 'A wandering soul in isolation, has no need for a place to belong.',
},
{
    id: 2,
    anime: 'Tsubasa Reservoir Chronicle',
    character: 'Kurogane',
    quote: 'I work by myself. Only for Princess Tomoyo.',
},
{
    id: 3,
    anime: 'Sakamoto desu ga?',
    character: 'Kubota Yoshinobu',
    quote: 'I understand now... What I really need to protect isn\'t myself, much less my money. It\'s my pride.',
},
{
    id: 4,
    anime: 'Naruto',
	character: 'Naruto Uzumaki',
	quote: 'People who continue to put their lives on the line to defend their faith become heroes and continue to exist on in legend.',
},
{
    id: 5,
    anime: 'Gintama',
	character: 'Gintoki Sakata',
	quote: 'Even if you\'re a main character, you can still die... I better be careful-ttebayo.',
},
{
    id: 6,
    anime: 'The Garden of Sinners',
	character: 'Aozaki Touko',
	quote: 'People do not cease to exist immediately after dying, as long as there are people who remember them.'
},
{
    id: 7,
    anime: 'Aoi Bungaku Series',
	character: 'K',
	quote: 'Those who do not want to advance spiritually are fools.'
},
{
    id: 8,
    anime: 'Monster',
	character: 'Wolfgang Grimmer',
	quote: 'Everyone in this world carries around their own sins, and they never go away...but that doesn\'t change the fact that we do what we must.'
},
{
    id: 9,
    anime: 'Yuri Yuri',
	character: 'KyÅko ToshinÅ',
	quote: 'If I can do it tomorrow, I won\'t do it today!'
},
{
    id: 10,
    anime: 'Yahari Ore No Seishun Love Come Wa Machigatteiru',
	character: 'Hachiman Hikigaya',
	quote: 'Excuses are meaningless. The tougher things get, the more likely people are to come to their own conclusions.',
    image: "hachiman-hikigaya.jpg",
},
{
    id: 11,
    anime: 'Haibane Renmei',
	character: 'Renmei Communicator',
	quote: 'To know your sin is to have no sin.',
    image: "renmei-communicator.jpg",
},
{
    id: 12,
    anime: 'FLCL',
	character: 'Naota Nandaba',
	quote: 'Nothing amazing happens here. Only the ordinary.',
    image: "naota-nandaba.jpg",
},
{
    id: 13,
    anime: 'Koutetsujou no Kabaneri',
	character: 'Horobi',
	quote: 'Those who underestimate their enemies will not last long in this world.',
    image: "horobi.jpg"
},
{
    id: 14,
    anime: 'Death Note',
	character: 'Light Yagami',
	quote: 'In this world, there are very few people who actually trust each other.',
    image: "light-yagami.jpg",
},
{
    id: 15,
    anime: 'Ano Hi Mita Hana No Namae Wo Bokutachi Wa Mada Shiranai',
	character: 'Tetsudō Hisakawa',
	quote: 'People do change, little by little.',
    image: "tetsudō-hisakawa.jpg",
},
{
    id: 16,
    anime: 'Sayonara Zetsubou Sensei',
	character: 'Sayonara Zetsubou Sensei',
	quote: 'A very small degree of hope is sufficient to cause the birth of love.',
    image: "sayonara-zetsubou-sensei.jpg",
},
{
    id: 17,
    anime: 'Fullmetal Alchemist',
	character: 'Riza Hawkeye',
	quote: 'The heroes during times of war, are nothing but mass murderers during times of peace.',
    image: "riza-hawkeye.jpg",
},
{
    id: 18,
    anime: 'Code:Breaker',
	character: 'Ogami Rei',
	quote: 'I dislike things. When a person dies, their things are left behind. I`d like to take care of mine ahead of time.',
    image: "ogami-rei.jpg",
},
{
    id: 19,
    anime: 'Death Note',
	character: 'Mello',
	quote: '*to Near* Which of us will get Kira first... it\'s a race!',
    image: "mello.jpg",
},
{
    id: 20,
    anime: 'Avatar: The Last Airbender',
	character: 'Azula',
	quote: 'Don\'t you know that fans only make flames stronger?',
    image: "azula.jpg",
},
{
    id: 21,
    name: "Jerusalem Artichoke",
    price: "$3.16",
    country: "United States",
    image: "jerusalem-artichoke.jpg",
},
{
    id: 22,
    name: "Leather Leaf Fern",
    price: "$9.41",
    country: "Brazil",
    image: "leather-leaf.jpg",
},
{
    id: 23,
    name: "Dried Apricots",
    price: "$7.42",
    country: "Brazil",
    image: "dried-apricots.jpg",
},
{
    id: 24,
    name: "Navel Orange",
    price: "$3.53",
    country: "Brazil",
    image: "navel-orange.jpg",
},
{
    id: 25,
    name: "Sunflower Oil",
    price: "$1.90",
    country: "Mexico",
    image: "sunflower-oil.jpg",
},
{
    id: 26,
    name: "Black Turtle Beans",
    price: "$4.67",
    country: "Canada",
    image: "turtle-beans.jpg",
},
{
    id: 27,
    name: "Bananas",
    price: "$2.64",
    country: "Canada",
    image: "bananas.jpg",
},
{
    id: 28,
    name: "Salami",
    price: "$8.72",
    country: "Brazil",
    image: "salami.jpg",
},
{
    id: 29,
    name: "Proscuitto",
    price: "$9.86",
    country: "Brazil",
    image: "proscuitto.jpg",
},
{
    id: 30,
    name: "Cranberries",
    price: "$5.85",
    country: "United States",
    image: "cranberries.jpg",
},
{
    id: 31,
    name: "Canteloupe",
    price: "$4.49",
    country: "United States",
    image: "canteloupe.jpg",
},
{
    id: 32,
    name: "Lemon",
    price: "$2.8Lemon5",
    country: "United States",
    image: "lemon.jpg",
},
{
    id: 33,
    name: "Pesto",
    price: "$2.67",
    country: "Brazil",
    image: "pesto.jpg",
},
{
    id: 34,
    name: "Grapefruit Juice",
    price: "$4.88",
    country: "Brazil",
    image: "grapefruit-juice.jpg",
},
{
    id: 35,
    name: "Curry Paste",
    price: "$2.02",
    country: "Brazil",
    image: "curry-paste.jpg",
},
{
    id: 36,
    name: "Avocado Oil",
    price: "$4.45",
    country: "Canada",
    image: "avocado-oil.jpg",
},
{
    id: 37,
    name: "Queso Fresco",
    price: "$9.24",
    country: "Canada",
    image: "queso-fresco.jpg",
},
{
    id: 38,
    name: "Key Lime Pie",
    price: "$5.32",
    country: "Mexico",
    image: "key-lime-pie.jpg",
},
{
    id: 39,
    name: "Granny Smith Apple",
    price: "$2.12",
    country: "United States",
    image: "granny-smith.jpg",
},
{
    id: 40,
    name: "Morning Glory Muffin Mix",
    price: "$9.22",
    country: "Brazil",
    image: "muffin-mix.jpg",
},
{
    id: 41,
    name: "Heavy Whipping Cream",
    price: "$8.78",
    country: "Brazil",
    image: "heavy-cream.jpg",
},
{
    id: 42,
    name: "Red Bell Pepper",
    price: "$9.03",
    country: "Brazil",
    image: "red-bell-pepper.jpg",
},
{
    id: 43,
    name: "Perrier",
    price: "$9.36",
    country: "United States",
    image: "perrier.jpg",
},
{
    id: 44,
    name: "Yukon Gold Potatoes",
    price: "$8.76",
    country: "Mexico",
    image: "yukon-potatoes.jpg",
},
{
    id: 45,
    name: "Salmon Fillets",
    price: "$6.21",
    country: "United States",
    image: "salmon-fillets.jpg",
},
{
    id: 46,
    name: "Tilapia Fillets",
    price: "$4.37",
    country: "Mexico",
    image: "tilapia.jpg",
},
{
    id: 47,
    name: "Tomato Pesto",
    price: "$9.70",
    country: "Brazil",
    image: "tomato-pesto.jpg",
},
{
    id: 48,
    name: "Oil - Olive Bertolli",
    price: "$8.92",
    country: "Brazil",
    image: "olive-oil.jpg",
},
{
    id: 49,
    name: "Tear Drop Yellow Tomatoes",
    price: "$3.32",
    country: "Mexico",
    image: "yellow-tomatoes.jpg",
},
{
    id: 50,
    name: "Smoked Paprika",
    price: "$8.31",
    country: "Brazil",
    image: "smoked-paprika.jpg",
},
];

export default mock;